services:

    gp_webpack.asset_collector:
        class: GoldenPlanet\WebpackBundle\Service\AssetCollector
        public: false
        arguments:
            - '@gp_webpack.error_handler'

    gp_webpack.asset_locator:
        class: GoldenPlanet\WebpackBundle\Service\AssetLocator
        arguments:
            - '@gp_webpack.alias_provider'

    gp_webpack.asset_name_generator:
        class: GoldenPlanet\WebpackBundle\Service\AssetNameGenerator
        public: false

    gp_webpack.asset_manager:
        class: GoldenPlanet\WebpackBundle\Service\AssetManager
        arguments:
            - '@gp_webpack.manifest_php_storage'
            - '@gp_webpack.asset_name_generator'
            - '@gp_webpack.entry_file_manager'

    gp_webpack.asset_resolver:
        class: GoldenPlanet\WebpackBundle\Service\AssetResolver
        public: false
        arguments:
            - '@gp_webpack.asset_locator'
            - '@gp_webpack.entry_file_manager'

    gp_webpack.entry_file_manager:
        class: GoldenPlanet\WebpackBundle\Service\EntryFileManager
        public: false
        arguments:
            - '%gp_webpack.entry_file.enabled_extensions%'
            - '%gp_webpack.entry_file.disabled_extensions%'
            - '%gp_webpack.entry_file.type_map%'

    gp_webpack.manifest_php_storage:
        class: GoldenPlanet\WebpackBundle\Service\ManifestPhpStorage
        public: false
        arguments:
            - '%gp_webpack.manifest_php_file_path%'

