services:

    gp_webpack.file_path.package_json:
        public: false
        class: stdClass
        factory: 'file_locator:locate'
        arguments: ['@@GoldenPlanetWebpackBundle/Resources/defaultWebpackConfig/package.json']

    gp_webpack.file_path.webpack_config_js:
        public: false
        class: stdClass
        factory: 'file_locator:locate'
        arguments: ['@@GoldenPlanetWebpackBundle/Resources/defaultWebpackConfig/symfony.webpack.config.js']
