services:

    gp_webpack.file.package_json:
        public: false
        class: stdClass
        factory: 'file_locator:locate'
        arguments: ['@@GoldenPlanetWebpackBundle/Resources/defaultConfig/package.json']

    gp_webpack.file.webpack_config_js:
        public: false
        class: stdClass
        factory: 'file_locator:locate'
        arguments: ['@@GoldenPlanetWebpackBundle/Resources/defaultConfig/webpack.config.js']

    gp_webpack.command.setup:
        class: GoldenPlanet\WebpackBundle\Command\SetupCommand
        tags:
            - { name: console.command }
        arguments: 
            - '@gp_webpack.file.package_json'
            - '@gp_webpack.file.webpack_config_js'
            - '%kernel.root_dir%/..'
            - '%kernel.root_dir%/config'

