services:

    gp_webpack.webpack_config_dumper:
        class: GoldenPlanet\WebpackBundle\Config\WebpackConfigDumper
        public: false
        arguments:
            - '%gp_webpack.webpack_entry_config_path%'
            - '%gp_webpack.webpack_config_path%'
            - '%gp_webpack.json_manifest_file_path%'
            - '%kernel.environment%'
            - '%gp_webpack.webpack_config_parameters%'

    gp_webpack.webpack_config_manager:
        class: GoldenPlanet\WebpackBundle\Config\WebpackConfigManager
        public: false
        arguments:
            - '@gp_webpack.alias_manager'
            - '@gp_webpack.asset_collector'
            - '@gp_webpack.webpack_config_dumper'
            - '@gp_webpack.asset_resolver'
            - '@gp_webpack.asset_name_generator'
            - '@gp_webpack.error_handler'

