language: php

sudo: false

php:
    - 5.6

env:
  global:
    - TRAVIS_NODE_VERSION="6"
    - COMPOSER_NO_INTERACTION="1"
  matrix:
    # install vendor packages with lowest version
    - COMPOSER_ARGS="--prefer-lowest"
    # install vendor packages with newest version and run Codeception with coverage
    - WITH_COVERAGE=true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

before_install:
    - if [ -z "${WITH_COVERAGE}" ]; then phpenv config-rm xdebug.ini; fi

install:
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

before_script:
    - bash -c "composer update $COMPOSER_ARGS"

script:
    - if [ "${WITH_COVERAGE}" == "true" ]; then COVERAGE_OPTION="--coverage-xml"; fi
    - vendor/bin/codecept run $COVERAGE_OPTION

after_success:
    # send coverage report to coveralls.io
    - if [ "${WITH_COVERAGE}" == "true" ]; then travis_retry php vendor/bin/coveralls; fi
