services:

    gp_webpack.alias_provider:
        class: GoldenPlanet\WebpackBundle\Provider\AliasProvider
        public: false
        arguments:
            - '@file_locator'
            - '%gp_webpack.enabled_bundles%'
            - '%gp_webpack.aliases.path_in_bundle%'
            - '%gp_webpack.aliases.additional%'
