parameters:

    gp_webpack.aliases.register_bundles: ''
    gp_webpack.aliases.bundle_default: ''
    gp_webpack.aliases.additional: ''

    gp_webpack.asset_providers: ''

    gp_webpack.bin.webpack.executable: ''
    gp_webpack.bin.webpack.tty_prefix: ''
    gp_webpack.bin.webpack.arguments: ''
    gp_webpack.bin.dev_server.executable: ''
    gp_webpack.bin.dev_server.tty_prefix: ''
    gp_webpack.bin.dev_server.arguments: ''
    gp_webpack.bin.disable_tty: ''

    gp_webpack.config.path: ''
    gp_webpack.config.parameters: ''

    gp_webpack.cache_dir: ''
    gp_webpack.working_dir: ''

    # Private parameters, not configurable in app's config.yml
    gp_webpack.webpack_entry_config_path: '%gp_webpack.cache_dir%/webpack.config.js'
    gp_webpack.manifest_file_path:        '%gp_webpack.cache_dir%/webpack_manifest.php'
    gp_webpack.json_manifest_file_path:   '%gp_webpack.cache_dir%/webpack_manifest.json'

