imports:

    - { resource: 'parameters.yml' }
    - { resource: 'resources.yml' }

    - { resource: 'providers/alias.provider.yml' }
    - { resource: 'providers/asset.provider.yml' }
    - { resource: 'providers/directory.provider.yml' }

    - { resource: 'services/asset-helper.services.yml' }
    - { resource: 'services/command.services.yml' }
    - { resource: 'services/error-handler.services.yml' }
    - { resource: 'services/twig.services.yml' }
    - { resource: 'services/webpack-compiler.services.yml' }
    - { resource: 'services/webpack-config.services.yml' }

