imports:

    - { resource: 'parameters.yml' }

    - { resource: 'services/aliases.yml' }
    - { resource: 'services/asset-helpers.yml' }
    - { resource: 'services/asset-providers.yml' }
    - { resource: 'services/commands.yml' }
    - { resource: 'services/error-handlers.yml' }
    - { resource: 'services/resources.yml' }
    - { resource: 'services/twig.yml' }
    - { resource: 'services/webpack-compiler.yml' }
    - { resource: 'services/webpack-config.yml' }

