parameters:

    # Not configurable in app's config.yml
    gp_webpack.webpack_entry_config_path: '%gp_webpack.cache_dir%/symfony.webpack.config.js'
    gp_webpack.manifest_file_path:        '%gp_webpack.cache_dir%/webpack_manifest.php'
    gp_webpack.json_manifest_file_path:   '%gp_webpack.cache_dir%/webpack_manifest.json'

